// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eimtietrpmelrxdszbmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpbXRpZXRycG1lbHJ4ZHN6Ym1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NTI1NDEsImV4cCI6MjA2MjAyODU0MX0.YpxerY_YNtQ31SDrC-0Sm7YsZ8lzFsXdcuDNDUC4x6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);